# Generated by Django 3.1.1 on 2020-09-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='slug',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
