# Generated by Django 3.1.1 on 2020-09-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_workimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workimage',
            name='image',
            field=models.ImageField(upload_to='works/'),
        ),
    ]
