# Generated by Django 3.1.1 on 2022-09-29 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_auto_20200909_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='year',
            field=models.IntegerField(default=2010),
            preserve_default=False,
        ),
    ]
