# Generated by Django 3.1.1 on 2022-09-29 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_work_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='present',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
