# Generated by Django 3.1.1 on 2022-09-29 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0006_work_present'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='year',
            field=models.IntegerField(default=''),
        ),
    ]
