# Generated by Django 3.1.1 on 2022-09-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0007_auto_20220929_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
