# Generated by Django 3.1.1 on 2022-09-29 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0008_work_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='slug',
        ),
    ]
